In [1]:
import numpy as np

In [3]:
# Creating a numpy array from a list
# numpy array is homogeneous
heights = [6.2, 4.2, 5.6, 5.12, 6.01]
np_heights = np.array(heights)
np_heights

array([6.2 , 4.2 , 5.6 , 5.12, 6.01])

In [4]:
# Indexing is the same as with a normal array
np_heights[0]

6.2

In [5]:
# There is another way of indexing. I want all the heights greater than or equal to 6
np_bools = np_heights > 6
np_bools

array([ True, False, False, False,  True])

In [6]:
# Pass the numpy array of booleans as an index to np_heights
np_heights[np_bools]

array([6.2 , 6.01])